# Distributed Storage Configuration
# Format: node.<ID>.ip=<IP> and node.<ID>.port=<PORT>
# For different computers, replace 127.0.0.1 with actual LAN IPs (e.g. 192.168.1.X)

node.A.ip=127.0.0.1
node.A.port=5000

node.B.ip=127.0.0.1
node.B.port=5001

node.C.ip=127.0.0.1
node.C.port=5002

node.D.ip=127.0.0.1
node.D.port=5003
