# Coordinator Election Configuration
node.A.ip=127.0.0.1
node.A.port=6000
node.A.priority=1

node.B.ip=127.0.0.1
node.B.port=6001
node.B.priority=2

node.C.ip=127.0.0.1
node.C.port=6002
node.C.priority=3

node.D.ip=127.0.0.1
node.D.port=6003
node.D.priority=4
